name: sound_fonts
description: Generates `Fonts` class to encapsulate all the fonts your Flutter application uses with the easy and understandable namings.
version: 0.1.2
homepage: https://github.com/lapuske/sound_fonts

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  analyzer: ">=8.0.0 <10.0.0"
  build: ">=3.0.1 <5.0.0"
  build_runner: ">=2.6.1 <3.0.0"
  source_gen: ">=3.1.0 <5.0.0"

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.0
